from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import joblib

_ROOT = Path(__file__).resolve().parent.parent
_PKG = Path(__file__).resolve().parent


def _model_path(name: str) -> Path:
    """Locates a model: pip package first, cloned repo second.

    `pip install noirebox` ships the .joblib files inside the package; a git
    clone leaves them in models/ (generated by make train). The fallback
    returns the repo path so the _load error message stays consistent with
    `make train`.
    """
    for base in (_PKG, _ROOT):
        candidate = base / "models" / name
        if candidate.exists():
            return candidate
    return _ROOT / "models" / name



_MODEL_PATHS = {
    "fr": _model_path("detector.joblib"),
    "en": _model_path("detector_en.joblib"),
}
_pipelines: dict[str, object] = {}


@dataclass
class MLDetection:
    """Same contract as guardrail.Incident — a drop-in replacement."""

    category: str
    score: float
    excerpt: str

    def as_dict(self) -> dict:
        return {"category": self.category, "score": round(self.score, 3),
                "excerpt": self.excerpt}


def model_available(lang: str = "fr") -> bool:
    path = _MODEL_PATHS.get(lang)
    return path is not None and path.exists()


def _load(lang: str):
    if lang in _pipelines:
        return _pipelines[lang]
    path = _MODEL_PATHS.get(lang)
    if path is None:
        raise ValueError(f"unknown language: {lang!r} (supported: {sorted(_MODEL_PATHS)})")
    if not path.exists():
        raise FileNotFoundError(
            f"models/detector{'' if lang == 'fr' else '_en'}.joblib missing — "
            f"run `make train{'-en' if lang == 'en' else ''}`"
        )
    _pipelines[lang] = joblib.load(path)
    return _pipelines[lang]


def predict_line(line: str, lang: str = "fr") -> MLDetection:
    """Classifies ONE line of text (a single transcript sentence)."""
    pipeline = _load(lang)
    category = pipeline.predict([line])[0]
    score = float(pipeline.predict_proba([line])[0].max())
    return MLDetection(category, score, line.strip()[:120])


def scan_ml(text: str, min_confidence: float = 0.5, lang: str = "fr") -> list[dict]:
    """Scans a text line by line → incidents in NoireBox format.

    Why line by line: the model was trained on sentences; feeding it 30
    lines at once would dilute the signals. We keep the granularity
    "one utterance = one verdict", ideal for the audit report.
    `min_confidence` discards verdicts that are too uncertain (the optimal
    threshold is debatable — this is the kind of false-positive/false-negative
    trade-off we own and document rather than hide).

    The `start`/`end` offsets (position of the line within the full text)
    are provided just like for regex incidents: the output format is
    identical, which lets the pipeline filter compromised lines regardless
    of the engine.
    """
    detections = []
    offset = 0
    for raw in text.splitlines():
        start, end = offset, offset + len(raw)
        offset = end + 1
        line = raw.strip()
        if not line:
            continue
        detection = predict_line(line, lang=lang)
        if detection.category != "clean" and detection.score >= min_confidence:
            entry = detection.as_dict()
            entry["start"], entry["end"] = start, end
            detections.append(entry)
    return detections
